version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: shahbaz42
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: nest
    networks:
      - localnetwork

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - localnetwork

volumes:
  redis:
    driver: local

networks:
  localnetwork:
