version: '3.8'

services:
  api:
    build: .
    command: yarn start:dev
    ports:
      - 3001:3001
    depends_on:
      - dev-db
      - redis
    networks:
      - localnetwork
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: shahbaz42
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: nest
    networks:
      - localnetwork
  redis:
    container_name: cache
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - localnetwork
volumes:
  redis:
    driver: local
networks:
  localnetwork:
